name:                diningPhilosophers
version:             0.1.0.0
github:              "nickager/diningPhilosophers"
license:             BSD3
author:              "Nick Ager"
maintainer:          "nick.ager@gmail.com"
copyright:           "Rocketbox Ltd"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nickager/diningPhilosophers#readme>

dependencies:
- base >= 4.7 && < 5
- random
- stm

library:
  source-dirs: src

executables:
  diningPhilosophers:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - diningPhilosophers

tests:
  diningPhilosophers-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - diningPhilosophers
